name: d3f_dependency_manager
version: 1.0.0+1
publish_to: none
description: d3f_dependency_manager.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  fimber: ^0.6.6
  flutter_hooks: ^0.18.5+1
  visibility_detector: ^0.3.3
  flutter_keyboard_visibility: ^5.3.0
  lottie: ^1.4.3
  flutter_svg: ^1.1.5
  shimmer: ^2.0.0
  intl: ^0.17.0
  jiffy: ^5.0.0
  rxdart: ^0.27.5
  path_provider: ^2.0.11
  path_provider_android: ^2.0.20
  path_provider_ios: ^2.0.11
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^3.5.0
  dio: ^4.0.6
  http_mock_adapter: ^0.3.3
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^2.3.7
  flutter_local_notifications: ^11.0.1
  flutter_native_timezone: ^2.0.0
  get: ^4.6.5
  equatable: ^2.0.5
  theme_tailor_annotation: ^1.0.3
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  flutter: 
    sdk: flutter
  d3f_shared: 
    git: 
      url: https://github.com/DanhDue-ExOICTIF/d3f_shared.git
      ref: develop
  d3f_core: 
    git: 
      url: https://github.com/DanhDue-ExOICTIF/d3f_core.git
      ref: develop
  d3f_login: 
    git: 
      url: https://github.com/DanhDue-ExOICTIF/d3f_login.git
      ref: develop
  d3f_inapp_purchase: 
    git: 
      url: https://github.com/DanhDue-ExOICTIF/d3f_inapp_purchase.git
      ref: develop

dev_dependencies: 
  flutter_lints: ^2.0.0
  test: ^1.21.4
  flutter_native_splash: ^2.2.10+1
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  hive_generator: ^1.1.3
  freezed: ^2.1.0+1
  get_cli: ^0.2.30
  flutter_gen_runner: ^5.0.1
  theme_tailor: ^1.0.6
  flutter_test: 
    sdk: flutter

flutter: 
  module: 
    androidPackage: com.danhdue.d3f_dependency_manager
    iosBundleIdentifier: com.danhdue.d3fDependencyManager
    androidX: true
  uses-material-design: true

